/* DROP CATEGORIES COLUMN IN SECURITYITEMS TABLE */
ALTER TABLE securityitems DROP COLUMN category;

/* DROP STATUS COLUMNS */
ALTER TABLE status DROP COLUMN clientid;

ALTER TABLE status DROP COLUMN securityitem;